### ISSUE TITLE
Execution failure

### ISSUE THREAD

**Issue by TheManoel** [Arquisoft/Loader_i1a#4]
I open this issue because of the only test that fails, that is **CitizenDaoMongoTest**. It is related with the class **CitizenDaoImplMongo**, and the failure message specifies the following:

> Not authorized on test to execute command...

**Comment by pedrytus** [comment]
At this moment, the error in the tests persists. From what Travis CI indicates, the failure is in _testRunInsert(alltests.LoadUsersTest)_ and the error is:

`databasetests.CitizenDaoMongoTest: Command failed with error 13: 'not authorized on test to execute command { createIndexes: "test", indexes: [ { key: { id: 1 } ... and so on ...`

**Comment by robertops18** [comment]
In lab class today, we reviewed the test that failed and notice that they were wrongly implemented by the previous developers. @jorgegnb and I took a look and fix them.
