### ISSUE TITLE
Document - Second deliverable

### ISSUE THREAD

**Issue by rimorD** [Arquisoft/Loader_i1a#6]
- Requirements of the Incidence Manager have been defined.

- Quality atributes added with their corresponding counterparts in other sections.

- Table 3 has been updated to show not only quality attributes but also constraints.

**Comment by robertops18** [comment]
- Main overview diagram built with Visual Paradigm during class by all members of the group.
- Details of the different parts of the diagram added to the document

**Comment by robertops18** [comment]
- BPMN diagram created
- Main overview diagram fixed
- Different tables filled

Document finished
